FROM ubuntu:24.04

LABEL maintainer=Matschieu

WORKDIR /home/www

COPY ./pcx pcx
COPY ./display.h display.h
COPY ./display.o display.o
COPY ./effets.c effets.c
COPY ./pcxr.c pcxr.c
COPY ./pcxr.h pcxr.h

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris

RUN dpkg --add-architecture i386
RUN apt update
RUN apt install -y gcc-multilib
RUN apt install -y --no-install-recommends libsdl1.2-dev:i386

RUN gcc -m32 -c effets.c pcxr.c
RUN gcc -m32 *.o -o pcxreader -lSDL `sdl-config --cflags –libs`

RUN ./pcxreader

#CMD ["/bin/bash"]

